stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - echo "Compilando a aplicação..."

test_job:
  stage: test
  script:
    - echo "Executando testes..."

deploy_job:
  stage: deploy
  script:
    - echo "Fazendo deploy da aplicação..."